### ISSUE TITLE
heatmap tweaks

### ISSUE THREAD

**Issue by martin-raden** [mmiladi/MutaRNA#19]
- ticks only every 10 
- vertical x-tick label (at the bottom?)
- 50%alpha gray lines every 50nt

**Comment by mmiladi** [comment]
>vertical x-tick label (at the bottom?)

You mean both top& bottom, left & right integer lables?

**Comment by mmiladi** [comment]
First two points fixed by https://github.com/mmiladi/MutaRNA/pull/22
For some unknown reason grid lines don't show up. Will be fixed for the revision ;)

**Comment by martin-raden** [comment]
> > vertical x-tick label (at the bottom?)
> 
> You mean both top& bottom, left & right integer lables?

I mean vertically aligned text labels at the botzom only (to aviid clash with title for longer seqs)

**Comment by mmiladi** [comment]
Good, that’s already the way in the recent version ,
