### ISSUE TITLE
Empty impact range diff matrix throws an exception

### ISSUE THREAD

**Issue by mmiladi** [mmiladi/MutaRNA#28]
In the procedure to get the ideal impact range in the zoomed mode, a fixed minimum probability is assigned. This causes a problem once all the probability differences are below the set threshold.

Do these the zoomed range list get empty:
https://github.com/mmiladi/MutaRNA/blob/master/bin/MutaRNA-plot.py#L129

Now the question is how to deal with this case:

- Should the the probability threshold be dynamically lowered (e.g. by 1/10) until the list is not empty?
- Should we report the full figure instead?

ping @martin-raden

**Comment by martin-raden** [comment]
dynamic decrease sounds best.

**Comment by martin-raden** [comment]
full figure could be backup plan...

**Comment by mmiladi** [comment]
Fixed via https://github.com/mmiladi/MutaRNA/pull/29
